[project]
name = "solrizer"
version = "1.0.0-dev"
dependencies = [
    "flask",
    "langcodes",
    "plastron-client",
    "plastron-models",
    "plastron-rdf",
    "plastron-repo",
    "plastron-utils",
    "python-dotenv",
    "requests-jwtauth",
]
requires-python = ">=3.12"

[project.optional-dependencies]
test = [
    "httpretty",
    "pytest",
    "pytest-cov",
    "pytest-datadir",
]

[project.entry-points.solrizer_indexers]
content_model = "solrizer.indexers.content_model:content_model_fields"
discoverability = "solrizer.indexers.discoverability:discoverability_fields"
page_sequence = "solrizer.indexers.page_sequence:page_sequence_fields"
iiif_links = "solrizer.indexers.iiif_links:iiif_links_fields"
